  
- hosts: localhost
  tasks:
   - name: Create App Service
     azure.azcollection.azure_rm_webapp:
       resource_group: dinesh
       name: myWinWebapptestdemo123
       plan: test-plan
       app_settings:
         testkey: testvalue
       frameworks:
         - name: "python"
           version: "7.0"
