- hosts: localhost
  vars:
    # Global Vars
    STATE: present
    REGION: ap-south-1

    # General Vars


  tasks:
    - name: Get VPC details
      ec2_vpc_net_info:
        region: "{{REGION}}"
      register: vpc_info
      
    - name: Gather s3 bukets Info  
      aws_s3_bucket_info:
      register: result
#     - name: gather information about AMI 
#       ec2_ami_info:
#         region: "{{REGION}}"
#       register: ami_info
    - debug:
        msg: "{{vpc_info}} {{result}}"
        
       
