- hosts: localhost
  # Parameter for creating lightsail instance
  vars:
    # Global Vars
    STATE: present
    REGION: ap-south-1

    # General Vars


  tasks:
    - amazon.aws.ec2_vpc_net_info:
      region: "{{REGION}}"
