- hosts: localhost
  vars:
    # Global Vars
    STATE: present
    REGION: ap-south-1

    # General Vars


  tasks:
    - name: Get VPC details
      ec2_vpc_net_info:
        region: "{{REGION}}"
      register: vpc_info
      
    - name: Gather s3 bukets Info  
      aws_s3_bucket_info:
      register: s3_buckets_info
      
    - name: Gather Cloudfront info
      cloudfront_info:
        summary: true
      register: cloud_front_info
   
    - name: Gather information about all ELBs
      community.aws.ec2_elb_info:
        register: elb_info
    - ansible.builtin.debug:
        msg: "{{ item.dns_name }}"
        loop: "{{ elb_info.elbs }}"
