- hosts: localhost
  vars:
    # Global Vars
    STATE: present
    REGION: ["ap-south-1","us-east-1"]

    # General Vars


  tasks:
    - name: Get VPC details
      ec2_vpc_net_info:
        region: "{{REGION}}"
      register: vpc_info
      
    - name: Gather s3 bukets Info  
      aws_s3_bucket_info:
      register: result
    - debug:
        msg: " {{vpc_info}} {{result}}"
        
       
