- hosts: localhost
  vars:
    # Global Vars
    STATE: present
    REGION: ap-south-1

    # General Vars


  tasks:
    - name: Get VPC details
      ec2_vpc_net_info:
        region: "{{REGION}}"
      register: vpc_info
      
    - name: Gather s3 bukets Info  
      aws_s3_bucket_info:
      register: s3_buckets_info
      
    - name: Gather Cloudfront info
      cloudfront_info:
        summary: true
      register: cloud_front_info
   
    - name: Gather information about all ELBs
      ec2_elb_info:
        region: "{{REGION}}"
      register: elb_info
      
    - name: Gather information about all instances
      ec2_instance_info:
        region: "{{REGION}}"
      register: ec2_instance_list
      
    - name: Gather information about all Internet Gateways for an account or profile
      ec2_vpc_igw_info:
        region: "{{REGION}}"
      register: igw_info
      
    - debug:
        msg: " {{vpc_info}} {{s3_buckets_info}} {{cloud_front_info}} {{elb_info}} {{ec2_instance_list}} ----------------- {{igw_info}}"
