- hosts: localhost
  vars:
    # Global Vars
    STATE: present
    REGION: ap-south-1

    # General Vars


  tasks:
    - name: Get VPC details
      ec2_vpc_net_info:
        region: "{{REGION}}"
      register: vpc_info
      
    - name: Gather s3 bukets Info  
      aws_s3_bucket_info:
      register: s3_buckets_info
      
    - name: Gather Cloudfront info
      cloudfront_info:
        summary: true
      register: cloud_front_info
   
    - name: Gather information about all ELBs
      ec2_elb_info:
        region: "{{REGION}}"
      register: elb_info
      
    - name: Gather information about all instances
      ec2_instance_info:
        region: "{{REGION}}"
      register: ec2_instance_list
      
    - name: Gather information about all Internet Gateways for an account or profile
      ec2_vpc_igw_info:
        region: "{{REGION}}"
      register: igw_info
      
    - name: List all managed nat gateways
      ec2_vpc_nat_gateway_info:
        region: "{{REGION}}"
      register: nat_gatewy_list
      
    - name: List all vpc peers
      ec2_vpc_peering_info:
        region: "{{REGION}}"
      register: list_all__vpc_peers
      
    - debug:
        msg: " ------ VPC-INFO ----- {{vpc_info}} ------ S3-BUCKETS-INFO ----- {{s3_buckets_info}} ------ CLOUD-FRONT-INFO ----- {{cloud_front_info}} ------ ELB-INFO ----- {{elb_info}} ------ EC2-INSTANCES-INFO ----- {{ec2_instance_list}} ------ IGW-INFO ----- {{igw_info}} ------ NAT-GATEWAY-INFO -----{{nat_gatewy_list}} ------ VPC-PEERING-LIST-INFO -----{{list_all__vpc_peers}} ------ VPC-PEERING-LIST-INFO -----"
