- hosts: localhost
  vars:
    # Global Vars
    STATE: present
    REGION: 
     - ap-south-1
     - us-east-1

    # General Vars


  tasks:
    - ec2_vpc_net_info:
        region: "{{REGION}}"
      register: vpc_info
    - debug:
        msg: "{{vpc_info}}"
       
