- hosts: localhost
  vars:
    # Global Vars
    # -------only one Region at a time------------

    REGION: ap-south-1
    OUTPUT_NEW_DIR_NAME: NEW
    PATH_OF_NEW_DIR: /home/output/test/
    FULL_PATH: "{{PATH_OF_NEW_DIR}}{{OUTPUT_NEW_DIR_NAME}}"

  tasks:
    - name: Get VPC details
      ec2_vpc_net_info:
        region: "{{REGION}}"
      register: vpc_info

    - name: Gather s3 buckets Info
      aws_s3_bucket_info:
      register: s3_buckets_info

    - name: Gather Cloudfront info
      cloudfront_info:
        summary: true
      register: cloud_front_info

    - name: Gather information about all ELBs
      ec2_elb_info:
        region: "{{REGION}}"
      register: elb_info

    - name: Gather information about all instances
      ec2_instance_info:
        region: "{{REGION}}"
      register: ec2_instance_list

    - name: Gather information about all Internet Gateways for an account or profile
      ec2_vpc_igw_info:
        region: "{{REGION}}"
      register: igw_info

    - name: List all managed nat gateways
      ec2_vpc_nat_gateway_info:
        region: "{{REGION}}"
      register: nat_gatewy_list

    - name: List all vpc peers
      ec2_vpc_peering_info:
        region: "{{REGION}}"
      register: list_all__vpc_peers

    - name: Gather information about all vpn connections
      ec2_vpc_vpn_info:
        region: "{{REGION}}"
      register: vpn_cnn_list

    - name: Find all existing efs
      efs_info:
        region: "{{REGION}}"
      register: efs_vol_list_info

    - name: find all existing IAM roles
      iam_role_info:
      register: iam_role_list_info

    - name: List all aws lambda function
      lambda_info:
        region: "{{REGION}}"
        query: all
      register: lambda_function_list

    - name: Get all RDS instances
      rds_instance_info:
        region: "{{REGION}}"
      register: all_rds_instance_info

    - name: List all hosted zones in route53
      route53_info:
        query: hosted_zone
      register: route53_hosted_zones_list

    - name: obtain all ACM certificates
      aws_acm_info:
        region: "{{REGION}}"
      register: acm_certificate_list

    - name: List all EIP addresses in the current region.
      ec2_eip_info:
        region: "{{REGION}}"
      register: regional_eip_addresses

    - name: List of all ec2_volumes in region
      ec2_vol_info:
        region: "{{REGION}}"
      register: ec2_volumes_info
      
    - set_fact: vpc_infoo="{{vpc_info}}"
    - set_fact: s3_bukets_infoo="{{s3_buckets_info}}"
    - set_fact: cloudfront_infoo="{{cloud_front_info}}"
    - set_fact: elb_infoo="{{elb_info}}"
    - set_fact: ec2_infoo="{{ec2_instance_list}}"
    - set_fact: igw_infoo="{{igw_info}}"
    - set_fact: nat_gw_infoo="{{nat_gatewy_list}}"
    - set_fact: vpc_peering_infoo="{{list_all__vpc_peers}}"
    - set_fact: vpn_cnn_infoo="{{vpn_cnn_list}}"
    - set_fact: efs_vol_infoo="{{efs_vol_list_info}}"
    - set_fact: iam_role_infoo="{{iam_role_list_info}}"
    - set_fact: lambda_fun_infoo="{{lambda_function_list}}"
    - set_fact: rds_instances_infoo="{{all_rds_instance_info}}"
    - set_fact: route53_infoo="{{route53_hosted_zones_list}}"
    - set_fact: acm_infoo="{{acm_certificate_list}}"
    - set_fact: eip_infoo="{{regional_eip_addresses}}"
    - set_fact: ec2_vol_infoo="{{ec2_volumes_info}}"
    
    - name: Creates directory
      file:
        path: /home/output/test/"{{OUTPUT_NEW_DIR_NAME}}"
        state: directory
        mode: '0777'
    
    - local_action: copy content={{ vpc_info }} dest=/home/output/test/{{OUTPUT_NEW_DIR_NAME}}/vpc_infoo.json
    - local_action: copy content={{ s3_bukets_infoo }} dest=/home/output/test/{{OUTPUT_NEW_DIR_NAME}}/s3_bukets_infoo.json
    - local_action: copy content={{ cloudfront_infoo }} dest=/home/output/test/{{OUTPUT_NEW_DIR_NAME}}/cloudfront_infoo.json
    - local_action: copy content={{ elb_infoo }} dest=/home/output/test/{{OUTPUT_NEW_DIR_NAME}}/elb_infoo.json
    - local_action: copy content={{ ec2_infoo }} dest=/home/output/test/{{OUTPUT_NEW_DIR_NAME}}/ec2_infoo.json
    - local_action: copy content={{ igw_infoo }} dest=/home/output/test/{{OUTPUT_NEW_DIR_NAME}}/igw_infoo.json
    - local_action: copy content={{ nat_gw_infoo }} dest=/home/output/test/{{OUTPUT_NEW_DIR_NAME}}/nat_gw_infoo.json
    - local_action: copy content={{ vpc_peering_infoo  }} dest=/home/output/test/{{OUTPUT_NEW_DIR_NAME}}/vpc_peering_infoo.json
    - local_action: copy content={{ vpn_cnn_infoo }} dest=/home/output/test/{{OUTPUT_NEW_DIR_NAME}}/vpn_cnn_infoo.json
    - local_action: copy content={{ efs_vol_infoo }} dest=/home/output/test/{{OUTPUT_NEW_DIR_NAME}}/efs_vol_infoo.json
    - local_action: copy content={{ iam_role_infoo }} dest=/home/output/test/{{OUTPUT_NEW_DIR_NAME}}/iam_role_infoo.json
    - local_action: copy content={{ lambda_fun_infoo }} dest=/home/output/test/{{OUTPUT_NEW_DIR_NAME}}/lambda_fun_infoo.json
    - local_action: copy content={{ rds_instances_infoo }} dest=/home/output/test/{{OUTPUT_NEW_DIR_NAME}}/rds_instances_infoo.json
    - local_action: copy content={{ route53_infoo }} dest=/home/output/test/{{OUTPUT_NEW_DIR_NAME}}/route53_infoo.json
    - local_action: copy content={{ acm_infoo }} dest=/home/output/test/{{OUTPUT_NEW_DIR_NAME}}/acm_infoo.json
    - local_action: copy content={{ eip_infoo }} dest=/home/output/test/{{OUTPUT_DIR_NAME}}/eip_infoo.json
    - local_action: copy content={{ ec2_vol_infoo }} dest=/home/output/test/{{OUTPUT_NEW_DIR_NAME}}/ec2_vol_infoo.json

    - debug:
        msg: " {{FULL_PATH}} {{cloudfront_infoo}}"
