- hosts: all
  become: true
  # Parameter for creating
  vars:
    # Global Vars
    STATE: present
    REGION: ap-south-1

    # General Vars

    # Do not change after this line

  tasks:
  - name: Upgrade/update all packages
    dnf:
      name: "*"
      state: latest
      update_only: true
      

  - name: Autoremove unneeded packages installed as dependencies
    dnf:
      autoremove: yes  
