- hosts: all
  become: true
  # Parameter for creating
  vars:
    # Global Vars
    STATE: present
    REGION: ap-south-1

    # General Vars

    # Do not change after this line

  tasks:
  - name: Upgrade/update all packages
    dnf:
      name: "*"
      state: latest
      update_only: true
      # security yes means only security update will update
      security: no
  # Below Package name(s) to exclude when state=present, or latest. This can be a list or a comma separated string.
      #exclude: apache2,nginx

  - name: Autoremove unneeded packages installed as dependencies
    dnf:
      autoremove: yes  
